import Head from 'next/head';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import randomHexColor from 'random-hex-color';
import Wave from 'react-wavify';
import { useEffect, useState } from 'react';
import Sky from '@/components/Sky';
const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const [innerHeight, setInnerHeight] = useState(null);
  const [innerWidth, setInnerWidth] = useState(null);

  useEffect(() => {
    setInnerHeight((prevHeight) => {
      return window.innerHeight;
    });
    setInnerWidth((prevWidth) => {
      return window.innerWidth;
    });
  }, []);


  return (
    <div className={styles.siteContainer}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Wave
          fill="black"
          stroke="black"
          strokeWidth={3}
          paused={false}
          options={{
            height: 20,
            amplitude: 22,
            speed: 0.35,
            points: 4,
          }}
          style={{
            position: 'absolute',
            width: '100%',
            height: '30%',
            opacity: '1',
            zIndex: '20',
            bottom: '0',
            left: '0',
            filter: `drop-shadow(0px -20px 10px 
        ${randomHexColor()}) drop-shadow(0px -20px 10px 
          ${randomHexColor()}) drop-shadow(0px -20px 10px 
            ${randomHexColor()})`,
          }}
        >
          <defs>
            <linearGradient id="gradient" gradientTransform="rotate(90)">
              <stop offset="10%" stopColor="#d4af37" />
              <stop offset="90%" stopColor="#f00" />
            </linearGradient>
          </defs>
        </Wave>
        <Wave
          fill="none"
          stroke="white"
          strokeWidth={4}
          paused={false}
          options={{
            height: 20,
            amplitude: 22,
            speed: 0.35,
            points: 4,
          }}
          style={{
            position: 'absolute',
            width: '100%',
            height: '20%',
            opacity: '.8',
            zIndex: '22',
            bottom: '0',
            left: '0',
          }}
        >
          <defs>
            <linearGradient id="gradient" gradientTransform="rotate(90)">
              <stop offset="10%" stopColor="#d4af37" />
              <stop offset="90%" stopColor="#f00" />
            </linearGradient>
          </defs>
        </Wave>
        <Wave
          fill="none"
          stroke="white"
          strokeWidth={4}
          paused={false}
          options={{
            height: 20,
            amplitude: 22,
            speed: 0.35,
            points: 4,
          }}
          style={{
            position: 'absolute',
            width: '110%',
            height: '10%',
            opacity: '.8',
            zIndex: '22',
            bottom: '0',
            left: '0',
          }}
        >
          <defs>
            <linearGradient id="gradient" gradientTransform="rotate(90)">
              <stop offset="10%" stopColor="#d4af37" />
              <stop offset="90%" stopColor="#f00" />
            </linearGradient>
          </defs>
        </Wave>

        <Sky innerWidth={innerWidth} innerHeight={innerHeight}></Sky>
      </main>
    </div>
  );
}
